package com.swipesapp.android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ATTACHMENT.
 */
public class Attachment {

    private Long id;
    private String identifier;
    private String service;
    private String title;
    private Boolean sync;
    private long taskId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Attachment() {
    }

    public Attachment(Long id) {
        this.id = id;
    }

    public Attachment(Long id, String identifier, String service, String title, Boolean sync, long taskId) {
        this.id = id;
        this.identifier = identifier;
        this.service = service;
        this.title = title;
        this.sync = sync;
        this.taskId = taskId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getService() {
        return service;
    }

    public void setService(String service) {
        this.service = service;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getSync() {
        return sync;
    }

    public void setSync(Boolean sync) {
        this.sync = sync;
    }

    public long getTaskId() {
        return taskId;
    }

    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
