package com.swipesapp.android.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.google.gson.annotations.SerializedName;
import com.swipesapp.android.sync.gson.LocalOnly;
// KEEP INCLUDES END

/**
 * Entity mapped to table ATTACHMENT.
 */
public class Attachment {

    @LocalOnly
    private Long id;
    private String identifier;
    private String service;
    private String title;
    @LocalOnly
    private Boolean sync;
    @LocalOnly
    private long taskId;

    // KEEP FIELDS - put your custom fields here
    @SerializedName("sync")
    private Integer syncInt;
    // KEEP FIELDS END

    public Attachment() {
    }

    public Attachment(Long id) {
        this.id = id;
    }

    public Attachment(Long id, String identifier, String service, String title, Boolean sync, long taskId) {
        this.id = id;
        this.identifier = identifier;
        this.service = service;
        this.title = title;
        this.sync = sync;
        this.taskId = taskId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getService() {
        return service;
    }

    public void setService(String service) {
        this.service = service;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getSync() {
        return sync;
    }

    public void setSync(Boolean sync) {
        this.sync = sync;
    }

    public long getTaskId() {
        return taskId;
    }

    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }

    // KEEP METHODS - put your custom methods here
    public Boolean getSyncInt() {
        return syncInt == 1;
    }

    public void setSyncInt(Boolean sync) {
        this.syncInt = sync ? 1 : 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj != null && obj instanceof Attachment) {
            if (((Attachment) obj).getIdentifier().equals(identifier)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public int hashCode() {
        return identifier.hashCode();
    }
    // KEEP METHODS END

}
